CREATE TABLE `datasourcemanager`.`datasource` (
  `id` CHAR(36) NOT NULL PRIMARY KEY,
  `ownerId` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `ownerName` VARCHAR(255) NOT NULL,
  `creationDateTime` DATETIME NOT NULL,
  `visibility` VARCHAR(255) NOT NULL,
  `downloadUri` VARCHAR(2048),
  `datasourceType` VARCHAR(255) NOT NULL,
  `jdbcUrl` VARCHAR(2048),
  `jdbcDriver` VARCHAR(512),
  `jdbcTable` VARCHAR(512),
  `jdbcQuery` LONGTEXT,
  `externalFileUrl` VARCHAR(2048),
  `hdfsPath` VARCHAR(2048),
  `libraryPath` VARCHAR(2048),
  `fileFormat` VARCHAR(255),
  `fileCsvIncludeHeader` BOOLEAN,
  `fileCsvConvert01ToBoolean` BOOLEAN,
  `fileCsvSeparatorType` VARCHAR(255),
  `fileCsvSeparator` VARCHAR(255),
  `googleSpreadsheetId` VARCHAR(1024),
  `googleServiceAccountCredentials` LONGTEXT,
  `googleSpreadsheetIncludeHeader` BOOLEAN,
  `googleSpreadsheetConvert01ToBoolean` BOOLEAN
) ENGINE=InnoDB;
